---
title: "puertoricomigrationflow"
author: "Wendy Prudencio"
---

## Quarto

```{r}
library(usethis)
```

```{r}
git_sitrep()
```

```{r}
use_git(message = "Create new project")
usethis::use_git_remote("origin", url = NULL, overwrite = TRUE)
```

```{r}
use_github(organisation = "bldgspatialdata22")
```




##Set-up packages
```{r}
library(tidycensus)
library(tidyverse)
library(tigris)
library(sf)
options(tigris_use_cache = TRUE)

options(tigris_class = "sf")
options(tigris_use_cache = TRUE)
census_api_key("CENSUS_API_KEY") 
"install = TRUE"
```

##Census data on all population

```{r}
state_pop <- get_estimates(geography = "state", product = "population")

state_pop
```

```{r}
unique(state_pop$variable)
```

##ASC estimates for sex, age, and latino/a/x orgin in Puerto Rico

```{r}
pr_age_hisp <- get_estimates(geography = "state", 
                             product = "characteristics", 
                             breakdown = c("SEX", "AGEGROUP", "HISP"),  
                             breakdown_labels = TRUE, 
                             state = "PR")

pr_age_hisp
```

##Migration per county/ municpality for 2015 in alphabetical order

```{r}
adjuntas15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "adjuntas",
  year = 2015
  )

adjuntas15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
aguada15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "aguada",
  year = 2015
  )

aguada15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
aguadilla15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "aguadilla",
  year = 2015
  )

aguadilla15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
aguasbue15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "aguas buenas",
  year = 2015
  )

aguasbue15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
aibonito15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "aibonito",
  year = 2015
  )

aibonito15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
anasco15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "anasco",
  year = 2015
  )

anasco15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
arecibo15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "arecibo",
  year = 2015
  )

arecibo15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
arroyo15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "arroyo",
  year = 2015
  )

arroyo15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
barcelo15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "barceloneta",
  year = 2015
  )

barcelo15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
barran15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "barranquitas",
  year = 2015
  )

barran15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
bayamon15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "bayamon",
  year = 2015
  )

bayamon15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
cabo15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "cabo rojo",
  year = 2015
  )

cabo15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
caguas15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "caguas",
  year = 2015
  )

caguas15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
camuy15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "camuy",
  year = 2015
  )

camuy15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
canov15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "canovanas",
  year = 2015
  )

canov15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
carolina15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "carolina",
  year = 2015
  )

carolina15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
catano15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "catano",
  year = 2015
  )

catano15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
cayey15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "cayey",
  year = 2015
  )

cayey15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
ceiba15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "ceiba",
  year = 2015
  )

ceiba15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
ciales15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "ciales",
  year = 2015
  )

ciales15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
cidra15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "cidra",
  year = 2015
  )

cidra15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
coamo15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "coamo",
  year = 2015
  )

coamo15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
comerio15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "comerio",
  year = 2015
  )

comerio15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
corozal15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "corozal",
  year = 2015
  )

corozal15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
culebra15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "culebra",
  year = 2015
  )

culebra15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
dorado15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "dorado",
  year = 2015
  )

dorado15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
fajardo15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "fajardo",
  year = 2015
  )

fajardo15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
florida15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "florida",
  year = 2015
  )

florida15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
guanica15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "guanica",
  year = 2015
  )

guanica15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
guayama15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "guayama",
  year = 2015
  )

guayama15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
guayanil15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "guayanilla",
  year = 2015
  )

guayanil15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
guaynabo15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "guaynabo",
  year = 2015
  )

guaynabo15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
gurabo15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "gurabo",
  year = 2015
  )

gurabo15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
hatillo15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "hatillo",
  year = 2015
  )

hatillo15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
hormi15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "hormigueros",
  year = 2015
  )

hormi15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
humacao15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "humacao",
  year = 2015
  )

humacao15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
isabela15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "isabela",
  year = 2015
  )

isabela15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
jayuya15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "jayuya",
  year = 2015
  )
jayuya15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
juana15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "juana diaz",
  year = 2015
  )

juana15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
juncos15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "juncos",
  year = 2015
  )

juncos15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
lajas15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "lajas",
  year = 2015
  )

lajas15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
lares15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "lares",
  year = 2015
  )

lares15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
lasmaria15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "las marias",
  year = 2015
  )

lasmaria15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
laspied15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "las piedras",
  year = 2015
  )

laspied15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
loiza15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "loiza",
  year = 2015
  )

loiza15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
luquillo15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "luquillo",
  year = 2015
  )

luquillo15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
manati15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "manati",
  year = 2015
  )

manati15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
maricao15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "maricao",
  year = 2015
  )

maricao15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
mayaguez15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "mayaguez",
  year = 2015
  )

mayaguez15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
moca15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "moca",
  year = 2015
  )

moca15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
morovis15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "morovis",
  year = 2015
  )

morovis15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
naguabo15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "naguabo",
  year = 2015
  )

naguabo15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
naranjito15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "naranjito",
  year = 2015
  )

naranjito15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
orocovis15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "orocovis",
  year = 2015
  )

orocovis15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
patillas15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "patillas",
  year = 2015
  )

patillas15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
penuela15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "penuelas",
  year = 2015
  )

penuela15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
ponce15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "ponce",
  year = 2015
  )

ponce15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
quebra15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "quebradillas",
  year = 2015
  )

quebra15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
rincon15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "rincon",
  year = 2015
  )

rincon15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
riog15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "rio grande",
  year = 2015
  )

riog15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
sabana15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "sabana grande",
  year = 2015
  )

sabana15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
salinas15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "salinas",
  year = 2015
  )

salinas15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
sangerman15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "san german",
  year = 2015
  )

sangerman15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
sanjuan15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "san juan",
  year = 2015
  )

sanjuan15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
sanlorenzo15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "san lorenzo",
  year = 2015
  )

sanlorenzo15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
sansebastian15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "san sebastian",
  year = 2015
  )

sansebastian15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
santai15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "santa isabel",
  year = 2015
  )

santai15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
toaalta15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "toa alta",
  year = 2015
  )

toaalta15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
toabaja15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "toa baja",
  year = 2015
  )

toabaja15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
trujillo15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "trujillo alto",
  year = 2015
  )

trujillo15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
utuado15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "utuado",
  year = 2015
  )

utuado15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
vegaalta15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "vega alta",
  year = 2015
  )

vegaalta15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
vegabaja15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "vega baja",
  year = 2015
  )

vegabaja15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
vieques15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "vieques",
  year = 2015
  )

vieques15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
villalba15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "villalba",
  year = 2015
  )

villalba15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
yabucoa15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "yabucoa",
  year = 2015
  )

yabucoa15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

```{r}
yauco15_flows <- get_flows(
  geography = "county",
  state = "PR",
  county = "yauco",
  year = 2015
  )

yauco15_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()
```

##Is there a way to run all these codes for the years remainding?\*

##Import data from NFIP

```{r}
install.packages("readxl")
```

```{r}
library("readxl")

nfip_data <- read_excel("/Users/wendyprudencio/Downloads/FEMANFIPClaims_PR.xlsx")
```

```{r}
use_readme_rmd()

use_cc0_license("Wendy Prudencio")
```
